name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" > gh_token.txt
          gh auth login --with-token < gh_token.txt
          rm gh_token.txt
      
      - name: Install and Configure Copilot
        env:
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Install GitHub CLI Copilot extension
          gh extension install github/gh-copilot
          
          # Create Copilot config directory
          mkdir -p ~/.config/gh-copilot
          
          # Save token in the correct format
          echo "{\"token\":\"$COPILOT_TOKEN\"}" > ~/.config/gh-copilot/token.json
          
          # Verify installation
          gh copilot --version
      
      - name: Fix Code with Copilot
        run: |
          # Create src directory if it doesn't exist
          mkdir -p src
          
          # Debug information
          echo "Current directory: $(pwd)"
          ls -la src/
          
          # Use gh copilot to suggest fixes
          # Add proper input to prevent EOF error
          gh copilot suggest "Fix the Java compilation errors in Main.java" < /dev/null > suggested_fix.txt
          
          # Debug the output
          echo "Suggested fix contents:"
          cat suggested_fix.txt || echo "No suggestions received."
          
          # Apply the suggested fix if available
          if [ -s suggested_fix.txt ]; then
            echo "Applying Copilot suggestion..."
            cp suggested_fix.txt src/Main.java
          else
            echo "No fixes suggested by Copilot. Exiting."
            exit 1
          fi
      
      - name: Verify Fixed Code
        run: |
          # Attempt to compile the fixed code
          if ! javac src/Main.java; then
            echo "Compilation failed after Copilot fix"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Fix Java compilation issues using GitHub Copilot"
            git push
          fi
