name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Configure GitHub CLI
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
                    
      - name: Install and Configure Copilot        
        env: 
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Install GitHub CLI Copilot extension
          gh extension install github/gh-copilot
          
          # Create Copilot config directory and token file
          mkdir -p ~/.config/gh-copilot
          echo "$COPILOT_TOKEN" > ~/.config/gh-copilot/token.json
          
          # Verify installation
          gh copilot --version
      
      - name: Fix Code with Copilot
        run: |
          # Use gh copilot to suggest fixes
          gh copilot suggest "Fix the Java compilation errors in src/Main.java" > suggested_fix.txt
          
          # Apply the suggested fix if available
          if [ -s suggested_fix.txt ]; then
            cat suggested_fix.txt > src/Main.java
          else
            echo "No fixes suggested by Copilot"
            exit 1
          fi
      
      - name: Verify Fixed Code
        run: |
          # Attempt to compile the fixed code
          if ! javac src/Main.java; then
            echo "Compilation failed after Copilot fix"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push
