name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.COP_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: Install Copilot CLI as GitHub CLI Extension
        run: |
          gh extension install github/gh-copilot
          gh copilot --help || echo "Copilot CLI installation failed"
      
      - name: Fix Code with Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.COP_TOKEN }}
        run: |
          # Use gh copilot to suggest fixes
          gh copilot suggest "Fix the Java compilation errors in src/Main.java" > suggested_fix.txt

          # Apply the suggested fix if available
          if [ -s suggested_fix.txt ]; then
            cat suggested_fix.txt > src/Main.java
          else
            echo "No fixes suggested by Copilot"
            exit 1
          fi
      
      - name: Verify Fixed Code
        run: |
          # Attempt to compile the fixed code
          if ! javac src/Main.java; then
            echo "Compilation failed after Copilot fix"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push
