name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install and Configure GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Setup GitHub CLI Authentication
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token
          gh auth status
      
      - name: Install GitHub Copilot CLI
        run: |
          gh extension install github/gh-copilot
          mkdir -p ~/.config/gh-copilot
          echo "${{ secrets.COPILOT_TOKEN }}" > ~/.config/gh-copilot/token.json
      
      - name: Check Initial Compilation
        id: compile
        continue-on-error: true
        run: |
          mkdir -p src
          if [ -f "Main.java" ]; then
            mv Main.java src/
          fi
          cd src
          if javac Main.java; then
            echo "compilation=success" >> $GITHUB_OUTPUT
          else
            echo "compilation=failed" >> $GITHUB_OUTPUT
          fi

      - name: Fix with Copilot
        if: steps.compile.outputs.compilation == 'failed'
        run: |
          cd src
          # Use gh copilot suggest to get fixes for Main.java
          gh copilot suggest -f Main.java > copilot_suggestions.txt
          
          # Apply the first suggestion
          if [ -s copilot_suggestions.txt ]; then
            cp Main.java Main.java.backup
            cat copilot_suggestions.txt > Main.java
          fi
      
      - name: Verify Fixed Code
        if: steps.compile.outputs.compilation == 'failed'
        id: verify
        continue-on-error: true
        run: |
          cd src
          if javac Main.java; then
            echo "fix_successful=true" >> $GITHUB_OUTPUT
          else
            echo "fix_successful=false" >> $GITHUB_OUTPUT
            # Restore backup if fix failed
            cp Main.java.backup Main.java
          fi
      
      - name: Create Pull Request
        if: steps.compile.outputs.compilation == 'failed' && steps.verify.outputs.fix_successful == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b fix-java-compilation
          git add src/Main.java
          git commit -m "fix: Auto-fix Java compilation issues"
          git push origin fix-java-compilation
          
          gh pr create \
            --title "🔧 Fix Java Compilation Issues" \
            --body "This PR contains automatic fixes for compilation errors in Main.java using GitHub Copilot suggestions." \
            --base main \
            --head fix-java-compilation
