name: Fix Java Compilation Issues with GitHub Copilot CLI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Install GitHub Copilot CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Install Copilot CLI globally
          sudo npm install -g @githubnext/github-copilot-cli
          
          # Configure Copilot CLI
          echo "$COPILOT_TOKEN" > ~/.copilot-token
          
          # Verify installation
          which github-copilot || echo "Copilot CLI not found in PATH"
          echo "PATH=$PATH"
          
          # Create config directory if it doesn't exist
          mkdir -p ~/.config/github-copilot
          
          # Store authentication
          echo "{\"token\":\"$COPILOT_TOKEN\"}" > ~/.config/github-copilot/hosts.json
          
      - name: Fix Code with Copilot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Full path to the CLI executable
          COPILOT_CLI=$(which github-copilot)
          
          echo "Using Copilot CLI at: $COPILOT_CLI"
          
          # Use Copilot CLI with full path
          "$COPILOT_CLI" fix "$(pwd)/src/Main.java" --output-file "$(pwd)/src/Main.java.fixed"
          
          # If fix was successful, replace original file
          if [ -f "src/Main.java.fixed" ]; then
            mv src/Main.java.fixed src/Main.java
          else
            echo "Copilot fix failed to generate output"
            exit 1
          fi
      
      - name: Verify Fixed Code
        run: |
          # Attempt to compile the fixed code
          if ! javac src/Main.java; then
            echo "Compilation failed after Copilot fix"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push
