name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Clone Repository
        run: |
          REPO_URL="https://github.com/${GITHUB_REPOSITORY}.git"
          git clone $REPO_URL workspace
          cd workspace
          echo "Current directory after clone: $(pwd)"
          ls -la
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      
      - name: Configure GitHub CLI
        run: gh auth login --web -h github.com
                    
      - name: Install and Configure Copilot        
        env: 
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Install GitHub CLI Copilot extension
          gh extension install github/gh-copilot
          
          # Create Copilot config directory and token file
          mkdir -p ~/.config/gh-copilot
          echo "$COPILOT_TOKEN" > ~/.config/gh-copilot/token.json
          
          # Verify installation
          gh copilot --version
            
      - name: Validate GitHub CLI Authentication
        run: gh auth status
      
      - name: Update GitHub CLI and Extensions
        run: gh extension upgrade --all
      
      - name: Check Directory and Compilation
        run: |
          cd workspace
          # Create src directory if it doesn't exist
          mkdir -p src
          
          # Change to src directory
          cd src
          
          # Debug information
          echo "Current directory: $(pwd)"
          ls -la
          
          # Try to compile the code first
          if javac Main.java; then
            echo "Compilation successful. No fixes needed."
            exit 0
          else
            echo "Compilation failed. Will attempt to fix with Copilot."
            # Continue to next step
          fi
      
      - name: Fix Code with Copilot        
        run: |
          cd workspace/src
          
          # Use gh copilot to suggest fixes
          gh copilot suggest "Fix the Java compilation errors in Main.java" < /dev/null > suggested_fix.txt
          
          # Debug the output
          echo "Suggested fix contents:"
          cat suggested_fix.txt || echo "No suggestions received."
          
          # Apply the suggested fix if available
          if [ -s suggested_fix.txt ]; then
            echo "Applying Copilot suggestion..."
            cp suggested_fix.txt Main.java
          else
            echo "No fixes suggested by Copilot. Exiting."
            exit 1
          fi
    
      - name: Verify Fixed Code        
        run: |
          cd workspace/src
          
          # Attempt to compile the fixed code
          if ! javac Main.java; then
            echo "Compilation failed after Copilot fix"
            exit 1
          fi
      
      - name: Commit Changes       
        run: |
          cd workspace
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push origin main
