name: Java Main File Check

on:
  pull_request:
    paths: ['src/Main.java']
  workflow_dispatch:

jobs:
  check-and-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Compile Main
        id: compile
        continue-on-error: true
        run: |
          javac src/Main.java
          echo "Compile result: $?"
        
      - name: Copilot Fix
        if: steps.compile.outcome == 'failure'
        uses: github/copilot-preview-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          copilot_token: ${{ secrets.COPILOT_TOKEN }}
          file_path: 'src/Main.java'
          fix_compilation_errors: true
          
      - name: Create Fix PR
        if: steps.compile.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'fix: Main.java compilation fixes'
          title: 'Fix Main.java'
          branch: fix-main-java
