name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update && sudo apt install gh -y

      - name: Configure GitHub CLI and Copilot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Temporarily unset GITHUB_TOKEN to avoid conflicts
          unset GITHUB_TOKEN
          
          # Configure GitHub CLI with GH_TOKEN
          gh auth setup-git
          
          # Install and configure Copilot
          gh extension install github/gh-copilot
          mkdir -p ~/.config/gh-copilot
          echo "$COPILOT_TOKEN" > ~/.config/gh-copilot/token.json
          
          # Verify authentication
          gh auth status
      
      - name: Check and Fix Java Code
        run: |
          # Find all Java files
          find . -name "*.java" -type f | while read -r file; do
            echo "Checking file: $file"
            
            if ! javac "$file" 2>/dev/null; then
              echo "Compilation failed for $file. Attempting to fix..."
              
              # Get Copilot suggestions using the correct syntax
              echo "Getting Copilot suggestions for $file..."
              FIXED_CODE=$(gh copilot suggest --target shell --comment "Fix Java compilation errors in this code:" < "$file")
              
              if [ ! -z "$FIXED_CODE" ]; then
                echo "$FIXED_CODE" > "$file"
                echo "Applied Copilot fix to $file"
              else
                echo "No fixes suggested by Copilot for $file"
              fi
            else
              echo "$file compiles successfully"
            fi
          done
      
      - name: Verify Fixed Code
        run: |
          find . -name "*.java" -type f -exec javac {} \;
      
      - name: Commit Changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push origin ${GITHUB_REF#refs/heads/}
