name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git credentials
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update && sudo apt install gh -y
      
      - name: Setup GitHub CLI and Copilot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Login to GitHub CLI
          echo "$GH_TOKEN" | gh auth login --with-token
          
          # Install Copilot extension
          gh extension install github/gh-copilot
          
          # Configure Copilot
          mkdir -p ~/.config/github-copilot/
          cat > ~/.config/github-copilot/hosts.json << EOF
          {
            "github.com": {
              "oauth_token": "$COPILOT_TOKEN",
              "user": "github-actions[bot]"
            }
          }
EOF
          
          # Verify auth status
          gh auth status
          gh copilot auth status
      
      - name: Check and Fix Code
        run: |
          # Create src directory if it doesn't exist
          mkdir -p src
          cd src
          
          echo "Current directory: $(pwd)"
          ls -la
          
          # Try to compile the code first
          if ! javac Main.java 2>/dev/null; then
            echo "Compilation failed. Will attempt to fix with Copilot."
            
            echo "Getting Copilot suggestions..."
            cat Main.java | gh copilot suggest --target shell > suggested_fix.txt
            
            if [ -s suggested_fix.txt ]; then
              echo "Copilot suggestion received:"
              cat suggested_fix.txt
              
              echo "Applying Copilot suggestion..."
              cat suggested_fix.txt > Main.java
            else
              echo "No fixes suggested by Copilot. Exiting."
              exit 1
            fi
          else
            echo "Compilation successful. No fixes needed."
            exit 0
          fi
      
      - name: Verify Fixed Code
        run: |
          cd src
          if ! javac Main.java; then
            echo "Verification failed: Code still doesn't compile"
            exit 1
          fi
          echo "Verification successful: Code compiles correctly"
      
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push origin ${GITHUB_REF#refs/heads/}
