name: Fix Java Compilation Issues with GitHub Copilot
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Setup GitHub CLI and Copilot
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Install GitHub CLI
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update && sudo apt install gh -y
          
          # Login to GitHub CLI
          echo "$GH_TOKEN" | gh auth login --with-token
          
          # Install Copilot extension
          gh extension install github/gh-copilot
          
          # Verify auth status
          gh auth status
          
      - name: Authenticate Copilot
        env:
          COPILOT_TOKEN: ${{ secrets.COPILOT_TOKEN }}
        run: |
          # Create directory for Copilot credentials
          mkdir -p ~/.config/github-copilot/
          
          # Write credentials file
          cat > ~/.config/github-copilot/hosts.json << EOF
          {
            "github.com": {
              "oauth_token": "$COPILOT_TOKEN",
              "user": "github-actions[bot]"
            }
          }
EOF
          
          # Verify Copilot auth
          gh copilot auth status
      
      - name: Check and Fix Java Code
        run: |
          # Create src directory if it doesn't exist
          mkdir -p src
          cd src
          
          if [ ! -f "Main.java" ]; then
            echo "Main.java not found in src directory"
            exit 1
          fi
          
          echo "Checking Main.java..."
          if ! javac Main.java 2>/dev/null; then
            echo "Compilation failed. Attempting to fix..."
            echo "Getting Copilot suggestions..."
            
            # Get Copilot suggestions
            SUGGESTION=$(cat Main.java | gh copilot suggest)
            
            if [ ! -z "$SUGGESTION" ]; then
              echo "$SUGGESTION" > Main.java
              echo "Applied Copilot fix to Main.java"
            else
              echo "No fixes suggested by Copilot"
              exit 1
            fi
          else
            echo "Main.java compiles successfully"
          fi
      
      - name: Verify Fixed Code
        run: |
          cd src
          if ! javac Main.java; then
            echo "Verification failed: Code still doesn't compile"
            exit 1
          fi
      
      - name: Commit Changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git add .
          git commit -m "Fix Java compilation issues using GitHub Copilot"
          git push origin ${GITHUB_REF#refs/heads/}
